### ISSUE TITLE
provide determined dependency load order

### ISSUE THREAD

**Issue by mightyaleksey** [css-modules/postcss-modules-resolve-imports#12]
For example: 

``` css
/* A.css */
.a {
  composes: a from './C.css';
}

.b {
  composes: b from './B.css';
  composes: b from './C.css';
}
```

should put deps in the order: `B.css`, `C.css`, `A.css`.

Also should warn about unclear order.
